<?php
/**
Plugin Name: Don't Log Health Checker
Plugin URI: https://github.com/guessi/yourls-dont-log-health-checker
Description: Don't Log Health Checker
Version: 1.0.1
Author: guessi
Author URI: http://github.com/guessi
*/

// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

function dlhc_is_health_check() {
    $user_agent = strtolower($_SERVER['HTTP_USER_AGENT']);

    // common health checker to skip (sort alphabetically)
    $keyword = array(
        '200pleasebot',
        '360spider',
        'adsbot-google',
        'ahrefsbot',
        'alexa-crawler',
        'alpha-robots',
        'amazon route 53',
        'amsua',
        'applebot',
        'archive.org_bot',
        'askjeeves',
        'baiduspider',
        'barkrowler',
        'bingbot',
        'bingpreview',
        'bitlybot',
        'blexbot',
        'butterflybot',
        'bytespider',
        'ccbot',
        'checkmarknetwork',
        'cliqzbot',
        'cloudflare',
        'cloudflare-healthcheck',
        'codeguard',
        'comodo spider',
        'comodo ssl checker',
        'comodo-certificate-spider',
        'comodo-webinspector-crawler',
        'comodospider',
        'commoncrawl',
        'copperegg',
        'crawler',
        'crawlerprocess',
        'crazywebcrawler',
        'curl',
        'cyberpatrol',
        'datadog',
        'deepcrawl',
        'discobot',
        'dotbot',
        'downnotifier',
        'downtimedetector',
        'duckduckbot',
        'elisabot',
        'epicbot',
        'ezooms',
        'exabot',
        'facebookexternalhit',
        'facebookbot',
        'feedfetcher-google',
        'feedly',
        'freshpingbot',
        'geckobot',
        'genieo',
        'getintent',
        'gigabot',
        'gomezagent',
        'google-assistant',
        'google-favicon',
        'google-image',
        'google-publisher-plugin',
        'google-site-verification',
        'google-structured-data-testing-tool',
        'google-web-light',
        'google-adsense',
        'google-adwords',
        'google-hc',
        'googlebot',
        'googlebot-image',
        'googlebot-news',
        'googlebot-video',
        'google-translate',
        'google-read-aloud',
        'googleweblight',
        'gotsitemonitor',
        'grepnetstatbot',
        'gtmetrix',
        'grapeshotcrawler',
        'hawkreader',
        'hotbot',
        'hosttracker',
        'httpunit',
        'httrack',
        'iascrawler',
        'infoseek',
        'inspingbot',
        'internetseer',
        'internetvista',
        'ips-agent',
        'irchkbot',
        'istellabot',
        'kube-probe',
        'larbin',
        'lexisnexisbot',
        'linkcheck',
        'linkstats',
        'linktiger',
        'loadimpactpageanalyzer',
        'loadimpactrload',
        'logicmonitor',
        'lycos',
        'maccrawler',
        'mappercmd',
        'mask-bot',
        'maxthon',
        'megaindex',
        'metajobbot',
        'mfibot',
        'microsoft-edge',
        'mj12bot',
        'mon.itor.us',
        'monitis.com',
        'monitor',
        'monitoring',
        'monitority',
        'montastic',
        'montools',
        'moz.com',
        'mozscape',
        'moziobot',
        'msnbot',
        'najdi.si',
        'naverbot',
        'netcraft',
        'netpeakspider',
        'newsblur',
        'nimbubot',
        'nmap',
        'nodestatsbot',
        'nomadrobot',
        'nomore404',
        'ntentbot',
        'onpagebot',
        'openlinkprofiler',
        'outbrain',
        'paessler',
        'panopta',
        'parsehub',
        'petalbot',
        'pingbot',
        'pingdom',
        'pingometer',
        'pinterestbot',
        'primalbot',
        'probethenet',
        'project25499',
        'proximic',
        'ptst',
        'qualidator',
        'qwantify',
        'radian6',
        'rogerbot',
        'seekportbot',
        'semrushbot',
        'seoengworldbot',
        'seokicks-robot',
        'seznam.cz',
        'seznambot',
        'siteanalyzer',
        'sitecheck',
        'siteimprove',
        'sitemonitor',
        'sitesnagger',
        'siteuptime',
        'socialrank',
        'sogou spider',
        'soso spider',
        'sputnikbot',
        'surfbot',
        'swiftbot',
        'tencenttraveler',
        'the knowledge ai',
        'twitterbot',
        'ubermetrics',
        'updown.io',
        'upguard',
        'uptime-kuma',
        'uptimerobot',
        'vagabondo',
        'vaultpress',
        'verifir',
        'voilabot',
        'w3c_validator',
        'webdata',
        'webdatastats',
        'webgator',
        'webmeup',
        'webmon',
        'webspidermount',
        'whatsapp',
        'whibse',
        'wikibot',
        'wisenutbot',
        'wotbox',
        'xenu link sleuth',
        'yahoo! slurp',
        'yandexbot',
        'yeti',
        'yetibot',
        'youdaobot',
        'zabbix',
        'zoho-crawler',
        'zoombot',
        'zoominfobot'
    );

    $is_hc = (str_replace($keyword, '', $user_agent) != $user_agent);

    return $is_hc;
}

// Hook register
yourls_add_filter('shunt_update_clicks', 'dlhc_skip_if_health_checker');
yourls_add_filter('shunt_log_redirect', 'dlhc_skip_if_health_checker');

// Skip if the user-agent shows that it is a service health check
function dlhc_skip_if_health_checker() {
    return dlhc_is_health_check();
}
